import numpy as np

def calculate_empirical_tail_dependence(u1, u2, q_lower=0.05, q_upper=0.95):
    """
    Estimates the empirical lower and upper tail dependence coefficients 
    from two arrays of uniformly distributed marginals (u1, u2).
    
    q_lower: Threshold for extreme downside (e.g., 5th percentile)
    q_upper: Threshold for extreme upside (e.g., 95th percentile)
    """
    n = len(u1)
    
    # --- Lower Tail Dependence ---
    # Number of times BOTH variables fall below the lower quantile q
    joint_lower_breaches = np.sum((u1 < q_lower) & (u2 < q_lower))
    # Approximation of C(q, q) / q using empirical counts
    lambda_lower = (joint_lower_breaches / n) / q_lower
    
    # --- Upper Tail Dependence ---
    # Number of times BOTH variables exceed the upper quantile q
    joint_upper_breaches = np.sum((u1 > q_upper) & (u2 > q_upper))
    # Approximation of survival copula bar_C(1-q, 1-q) / (1-q)
    lambda_upper = (joint_upper_breaches / n) / (1 - q_upper)
    
    return {
        "Threshold (q_lower)": q_lower,
        "Empirical Lower Tail Dependence": min(lambda_lower, 1.0), # Capped at 1.0 for probability bounds
        "Threshold (q_upper)": q_upper,
        "Empirical Upper Tail Dependence": min(lambda_upper, 1.0)
    }

# Example Usage: 
# Assuming u_asset_1 and u_asset_2 are uniform series (e.g., generated by ranking empirical data)
# tail_risk = calculate_empirical_tail_dependence(u_asset_1, u_asset_2)